language: node_js
node_js:
 - node
install:
 - npm install
script:
 - npm run build
 - npm run generate
deploy:
  provider: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: pageBranch