language: node_js
node_js:
 - node
install:
 - npm install
script:
 - npm run build
 - npm run generate
 - echo "Skipping tests"
 - echo $GITHUB_TOKEN
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: pageBranch
  local-dir: dist
  on:
    branch: master