language: node_js
node_js:
 - node
install:
 - npm install
script:
 - npm run build
 - npm run generate
deploy:
  provider: yo.chen
  skip_cleanup: true
  target-branch: pageBranch
  local-dir: dist
  github_token: $GITGUB_TOKEN_TEST
  keep_history: true
  on:
    branch: master