language: node_js
node_js:
 - node
install:
 - npm install
script:
 - npm run build
 - npm run generate
script:
  - echo "Skipping tests"
  - echo $GITHUB_ACCESS_TOKEN
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: pageBranch
  local-dir: dist
  on:
    branch: master